apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: datadriven
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: grafana
          image: ghcr.io/netserv-uah/grafana-datadriven:latest
          imagePullPolicy: Always
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: INFLUX_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: INFLUX_URL
            - name: INFLUX_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: INFLUX_USER
            - name: INFLUX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: INFLUX_PASSWORD
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: INFLUX_TOKEN
            - name: INFLUX_BUCKET
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: INFLUX_BUCKET
            - name: INFLUX_ORG
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: INFLUX_ORG
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: provisioning
              mountPath: /etc/grafana/provisioning
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
        - name: provisioning
          persistentVolumeClaim:
            claimName: grafana-provisioning

