apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu
  namespace: datadriven
  labels:
    app: ryu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu
  template:
    metadata:
      labels:
        app: ryu
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: ryu
        image: ghcr.io/netserv-uah/ryu-datadriven:latest
        env:
          - name: INFLUXDB_URL
            valueFrom:
              secretKeyRef:
                name: ryu-secrets
                key: INFLUXDB_URL
          - name: INFLUXDB_TOKEN
            valueFrom:
              secretKeyRef:
                name: ryu-secrets
                key: INFLUXDB_TOKEN
          - name: INFLUXDB_ORG
            valueFrom:
              secretKeyRef:
                name: ryu-secrets
                key: INFLUXDB_ORG
          - name: INFLUXDB_BUCKET
            valueFrom:
              secretKeyRef:
                name: ryu-secrets
                key: INFLUXDB_BUCKET
          - name: BENTO_URL
            valueFrom:
              secretKeyRef:
                name: ryu-secrets
                key: BENTO_URL
