name: Build and Push to GHCR
run-name: ${{ github.actor }} estÃ¡ compilando contenedores :)
on:
  push:
    branches:
      - k8s-deploy-datadriven

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repo owner lowercase
        id: vars
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Grafana image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.owner }}/grafana-datadriven:latest ./kubernettes/containers/Migrados/grafana
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/grafana-datadriven:latest

      - name: Build and push InfluxDB image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.owner }}/influxdb-datadriven:latest ./kubernettes/containers/Migrados/influxdb
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/influxdb-datadriven:latest
      
      - name: Build and push Ryu image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.owner }}/ryu-datadriven:latest ./kubernettes/containers/Migrados/ryu
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/ryu-datadriven:latest
      - name: Build and push BentoML image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.owner }}/bentoml-datadriven:latest ./kubernettes/containers/Migrados/bentoml
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/bentoml-datadriven:latest
